### ISSUE TITLE
Matter overdrive has completely killed the FC SF4 instance.

### ISSUE THREAD

**Issue by cpw** [DarkPacks/SkyFactory-4#1006]
## Bug Report

Matter Overdrive seems to have completely killed the FC sky factory 4 server. It seems to have spawned an insanely large number of entities. Trying to remove the entities is resulting in concurrent modification crashes, with little to zero progress. Trying to remove the mod results in a script crash. The server is probably going to need to be completely reset.

## Expected Behaviour

That the server doesn't become irredeemably corrupted by a mod.

## Possible Solution

Probably needs a significant overhaul of how the mobs and mob spawning for matter overdrive is implemented to prevent it killing servers.

## Steps to Reproduce (for bugs)

1. I have preserved the FC instance. I can share it wherever.

## Logs

* Client/Server Log:
* Crash Log:
I can provide the 38 crash logs if you wish. Summary: the TPS dropped so low due to mob count that it was triggering the 60s tick crash restart. Attempts to kill the entities `kill @e[type=matteroverdrive:rogue_android]` resulted in ConcurrentModificationException crashes related to the mob's state. I'm not going to spend the next n hours or days rerunning in the vain hope that I'm slowly killing off the mobs. I suspect something more fundamental, like a broken spawning mechanism, is the root cause.

## World Information

* Preset: lostcities

* Prestige: probably? (Defaults to yes, yes?)

* Modpack Version world created in: 4.0.7?

* Additional Content Installed: A discord chat connection mod.

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

It's a server crash.

## Server Information
* Java Version: 1.8 171
* Operating System: Linux
* Hoster/Hosting Solution: Forgecraft!
* Sponge (Non-Vanilla Forge) Server: It's forgecraft.

**Comment by Darkosto** [comment]
Shared with the mod dev of Matter Overdrive. We'll see if we can come up with a solution.

**Comment by shinyafro** [comment]
just remove the region file effected or roll it back

**Comment by Darkosto** [comment]
So, I've looked into this a bit more a few times since this report was made. From what I'm seeing here in the report I don't think this is a Matter Overdrive specific bug. This is most likely due to someone on the server upgrading a spawner and not turning it off. Everything you have given me so far I can replicate by upgrading a mob farm and leaving it running. I can replicate this issue with ANY mob given the right upgrades. 

I have not had anyone else replicate this issue outside of a player created environment with upgraded spawners. Which is why this issue was unable to be resolved. I've also spoken the mod dev and nothing seems to be causing this issue you have on their end. My guess is, if you turned off the spawner upgrade mechanics of Apotheosis this issue would probably go away.

**Comment by cpw** [comment]
Closing

**Comment by TacocaTYT** [comment]
try setting it to peaceful since that deletes mobs
