### ISSUE TITLE
Can't pour Blazing Pyrotheum from Melter into Cauldron

### ISSUE THREAD

**Issue by Coloradohusky** [DarkPacks/SkyFactory-4#1122]
## Bug Report
Trying to pour Blazing Pyrotheum into a Cauldron in order to make a Magma Slime Sapling, nothing comes out of the Faucet when I right-click

## Expected Behaviour
Blazing Pyrotheum should pour out of the Faucet and into the Cauldron

## Possible Solution
Maybe there's something in the config files that could be edited to fix it?

## Steps to Reproduce (for bugs)
1. Melt Pyrotheum Dust in a Melter
2. Attach a Faucet on any side of the Melter
3. Place a Cauldron underneath the Faucet
![2019-07-04_10 08 00](https://user-images.githubusercontent.com/45430066/60672758-2bb8b200-9e44-11e9-86e3-4f20f78f2b15.png)

## World Information

* Preset: SkyFactory 4

* Prestige: Yes

* Modpack Version world created in: 4.0.8

* Additional Content Installed: [Better Builder's Wands](https://www.curseforge.com/minecraft/mc-mods/better-builders-wands)

## Client Information

* Modpack Version: 4.0.8
* Java Version: Java 8 Update 211
* Launcher Used: MultiMC 5
* Memory Allocated: 6144 MB
* Server/LAN/Single Player: Single-Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by jeroenwienk** [comment]
You can put a bucket on the casting table and pour the Pyrotheum on it. This will give you a bucket which you can do whatever you like with for instance putting it in a cauldron. I dont think this is fixable since it is a mod incompatibility issue and it doesn't seem that there is any config setting to change this(checked tinkers, tinkerscomplement, morecauldrons and inspirations).

**Comment by sk2048** [comment]
The cauldron can only accept increments of 250mB, Tinker's faucets pipe 6mB a tick. They will not work together. The bucket method suggested above will work. As will using Cyclic's fluid pipes.
