### ISSUE TITLE
Massive server tick lag followed by crash

### ISSUE THREAD

**Issue by Aeobrix** [DarkPacks/SkyFactory-4#1268]
## Bug Report
Running a private server for myself, a player on the same local network, and another player connecting over the internet. I both run the server and my client on my PC; the client uses the MultiMC launcher. I have an Intel Core i5-8600K (not overclocked), and 16GB RAM.
My brother was repeatedly getting lag and complete disconnections, but I couldn't find any evidence of a network issue causing the lag. This was soon followed by both me and the other local player getting a large amount of lag from the server (no response to inputs or updates of other players) before both also suffering a disconnect. During the lag spike Task Manager showed no stress on either the CPU or RAM, and the Server RAM usage did not even approach the 8GB max allocated for it. I have attached a screenshot of the crash as it appeared in the server console, and both crash reports that were generated (not sure if its normal for more than one to generate?). We have experienced the lag before on 1 occasion, however the server did not fully crash, and both of us local players eventually resynced. Since this is only the 3rd session we have had playing on the server, we have experienced the huge lag spike 2/3 times now!
We are very early in the game, having not even unlocked hoppered bonsai tress, so it cannot be bad pipes/wires causing the lag. Any help would be greatly appreciated, as this is the first time I've run a server, and I am a bit out of my depth! Let me know I should upload any more information.

## Steps to Reproduce (for bugs)
Not known, but it's happened twice out of 3 play sessions. We weren't doing the same thing though.

## Crash Log:
https://pastebin.com/Gbye3Uzk
https://pastebin.com/fvn9VFDh
Screenshot of server console after crash:
![Screenshot from crash](https://user-images.githubusercontent.com/56048004/65997705-bfc10680-e491-11e9-8a14-238105547b2a.png)

## World Information
* Preset: Sky Factory 4
* Prestige: No
* Modpack Version world created in: 4.0.8

## Client Information
* Modpack Version: 4.0.8
* Java Version: Version 8 Update 221
* Launcher Used: MultiMC
* Memory Allocated: 12GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 4.0.8
* Operating System: Windows 10
* Hoster/Hosting Solution: Running on PC
* Sponge (Non-Vanilla Forge) Server: No?

**Comment by sam-kirby** [comment]
There are two different crash reports here which do not seem at all related.

One is a concurrent modification exception whilst ticking the world. This is a frustratingly generic error, but I would recommend updating to 4.1.0 (currently in beta) as various CMEs were fixed in this update among other things.

The other is the issue you spend most of your time describing relates to a single tick taking 60 seconds to process, which is the cutoff time set by default in server.properties.

The crash report describes your remote friend disconnecting from the server (no details as to why), and as a result the server tries to save their player data. It spends most of a minute trying to do this, and seems to struggle with getting access to the file. This is consistent with what you observed - there would be no spike in CPU activity as all the server is doing for a minute is sitting there waiting for access to a file.

There are a lot of reasons drive access may fail. The most common is due to external backup software such as Onedrive blocking access to folders whilst they back them up. Avoid installing your server in a folder monitored by any such applications. Another is the drive being used excessively by other applications meaning it cannot service all requests. Keeping background usage to a minimum will help here.

There are lots of other potential issues, but really this is outside the scope of something that can be considered an issue with the pack and so further discussion doesn't really belong here. Someone on the discord may have further ideas; https://discord.gg/darkosto
