### ISSUE TITLE
crash while respawning

### ISSUE THREAD

**Issue by AnonymousDeveloper65535** [DarkPacks/SkyFactory-4#1285]
## Bug Report

When I die and hit respawn I crash. Other people in the server has this issue
## Expected Behaviour

I expect not to crash. It should spawn you at your spawn location. Instead I crash.
## Steps to Reproduce (for bugs)

1. Fall to your death or get killed by a mob
2. Hit respawn

## Logs

* Client/Server Log:

* Crash Log: 
https://pastebin.com/ehhzA6W0

## World Information

* Preset: Default

* Prestige: disabled using a command after having it enabled

* Modpack Version world created in: 4.0.8

* Additional Content Installed: Optifine

## Client Information

* Modpack Version: 4.1.0
* Java Version: 1.8.0_221(64 bit)
* Launcher Used: ATL Launcher(but ppl who used twitch had same issue)
* Memory Allocated: 3 GB
* Server/LAN/Single Player: Server
* Optifine Installed: yes(but others who crashed didn’t have it)
* Shaders Enabled: no

**Comment by killerkid745** [comment]
Hi,

You can track this crash really easily (I also had the same issue!)

It first lets you know that you are crashing due to the following:
Description: Rendering Block Entity

Scrolling down to the detailed walkthrough of the error, it shows you the exact block that crashes you too! (not really sure how to tell exact position though)

Underneath Block Entity Details, you can see it is referring to a PlayerStatue Entity. This boils down to the Statues mod, specifically the Statue that shows off a Player's skin.
I removed all of these statues placed around my base and tested respawning and it worked as normal.

**Comment by astynax777** [comment]
I had the same error in my crash report, removed all statues (threw all into void) and it still crashed again when a player was killed by another player.  It's not consistent, but always a result of a player kill.

**Comment by service-fabric-dev** [comment]
I get the [same error](https://pastebin.com/qgiiG4jv) as OP, coming from the PlayerStatueRenderer.  I have no "statue" blocks placed around my base. This is a relatively new world on Skiiiilands.

The main exception seems to say it's checking an air block for a direction enum property.  The dumped StateContainer does, in fact, have no PropertyDirection property.  Is it possible this is a desynch in player location vs death location?

**Comment by ar1a** [comment]
i'm getting this too!

**Comment by cherrykoda** [comment]
We had this start occuring on a server yesterday - after reading the reports here I can say the de-sync theory is plausible. The crash seems to happen when the player is displaced during/after death. It happened when killed by the android gun (player killed another player), when dying during a fall, when dying followed by falling post-dead, and when dying in water/lava flow.

We do have several statues placed on the map, that we've gotten from graves, but the crashing didnt start until at least 2 or 3 statues were around the map.

Hope this helps!

------------------- CONSOLE ------------------
[2020-01-04 22:52:07] [Server thread/INFO] [FML]: Unloading dimension 144

[2020-01-04 22:53:12] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Anomaleigh_ moved too quickly! 0.0,332.0143600124883,0.0

[2020-01-04 22:53:19] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: Anomaleigh_ moved too quickly! 0.0,335.0577083927641,0.0

[2020-01-04 22:53:24] [Server thread/INFO] [minecraft/DedicatedServer]: Anomaleigh_ fell from a high place

[2020-01-04 22:53:39] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Anomaleigh_ lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

[2020-01-04 22:53:39] [Server thread/INFO] [minecraft/DedicatedServer]: Anomaleigh_ left the game

[2020-01-04 23:00:00] [Server thread/INFO] [tombstone]: All players have been successfully backed up

**Comment by marcusbeckerman** [comment]
I'm also experiencing this.

Crash log:
https://pastebin.com/yuqN609Q

**Comment by Johnyknowhow** [comment]
Same here. Statues on island, crash on respawn (only sometimes though). 

[crash-2020-04-16_16.21.52-client.txt](https://github.com/DarkPacks/SkyFactory-4/files/4490139/crash-2020-04-16_16.21.52-client.txt)

**Comment by Y2Nk4** [comment]
We found out a similar issue. So basically, I turned off the server's online mode, and some of my friends logged in the game in offline mode. The client was laggy(1 fps) when a statue of an offline-mode player dropped. But nothing will happen if it's from an online-mode player.
It's more like a client-side issue. When we clear that statue object, everything gets fine again. 
So I recommend disabling `PlayersDropStatue` the in `config/statues.cfg` if you want to allow the offline player to log into the server.

I think it's because the statues mode is trying to polling the skin of the player, but not succeed due to it's a fake UUID

**Comment by icanotc** [comment]
not for me tho, our server is in online mode and it still crash sometimes

**Comment by Y2Nk4** [comment]
> not for me tho, our server is in online mode and it still crash sometimes

Do you mean a server crash or? But 'cause my friends and I only played for about 2weeks, so maybe that's the reason why we didn't experience that. But still, I recommend you to update the statue mod or simply disable the `PlayersDropStatue` to see if it will fix the issue. If yes, that means it's caused by the statue mod.
Or there is another way, if the client crashes, you can try to check the client crash log to see if it mentions any mod.

**Comment by sam-kirby** [comment]
You should probably just update the pack to 4.2.0 which is out on Curseforge.
