### ISSUE TITLE
Seemingly random crash, then unable to join Vanilla Bukkit server

### ISSUE THREAD

**Issue by Wunst** [DarkPacks/SkyFactory-4#1386]
When playing on a server, random client crashes sometimes occur without crash report. Here's the latest log:
[2020-03-06-2.log](https://github.com/DarkPacks/SkyFactory-4/files/4301655/2020-03-06-2.log)

After this, a Java Platform task using all GPU capacity was running and I couldn't start the modpack again. After a restart, I was unable to join servers like hypixel.net in Vanilla, which gave the following crash:
[hs_err_pid2768.log](https://github.com/DarkPacks/SkyFactory-4/files/4301648/hs_err_pid2768.log)

**Comment by sam-kirby** [comment]
Your "Vanilla" crash seems to be due to there not being enough RAM available to the JRE.

This is likely a result of you running other memory hungry software on your machine, which would include SF4 if you're running it at the same time, but likely not otherwise. You could try and reduce the maximum heap allocation, or a increase the initial size so that any errors are caught early for Vanilla.

Speaking of which, your log does not appear to contain a crash, though it does suddenly end. If you edited it, it's possible whatever program you used to do so truncated the log.

There is nothing to act on here in relation to SF4 so I'm closing this issue. Should you wish to resubmit an issue, please do follow the template next time.

**Comment by Wunst** [comment]
Thank you, likely something was running in background because another restart fixed the problem.
