### ISSUE TITLE
Disabling Headcrumbs also disables Animal Crops recipes

### ISSUE THREAD

**Issue by elisionducoeur** [DarkPacks/SkyFactory-4#1465]
## Bug Report

Disabling Headcrumbs, Twitchcrumbs, and Wither Crumbs disables hostile mob seed recipes in Animal Crops. These 3 mods may need to be disabled #1460 

## Expected Behaviour

The three mods above shouldn't affect Animal Crops.

## Steps to Reproduce (for bugs)

1. Play SF4 with all mods enabled, Animal Crops has all recipes
2. Disable Headcrumbs, Twitchcrumbs, and Wither Crumbs, Animal Crops doesn't have recipes for hostile mob seeds
3. Renable Headcrumbs, Twitchcrumbs, and Wither Crumbs, Animal Crops has recipes for hostile mob seeds

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Normal (Regular minecraft, not the floating island one)

* Prestige:  No

* Modpack Version world created in: 4.1.0

* Additional Content Installed:

## Client Information

* Modpack Version: 4.1.0
* Java Version: 
* Launcher Used: MultiMC
* Memory Allocated: 16 GB
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: N/A

**Comment by sam-kirby** [comment]
Removing mods will always impact crafttweaker scripting that depends on them. This is not something that is going to change. We have never recommended removing those mods.

Since initially investigating the issue you linked I have retested the API twice and have been unable to trigger any kind of error response, valid or invalid, so perhaps another change by Mojang has rendered this information obsolete. The test world I created with hundreds of *crumbs mobs that was previously triggering a rate limit response and crashing no longer hits the rate limit. There isn't really any way of knowing if this applies to everyone without more information though. To help with this, could you please indicate the time you experienced your issue.

Another way of dealing with this issue without taking a sledgehammer to the pack is to set the probability of human mobs spawning to zero. This minimises calls to Mojang's API, reducing the chance of hitting a rate limit significantly.

See https://github.com/DarkPacks/SkyFactory-4/blob/master/src/config/headcrumbs.cfg#L120
