### ISSUE TITLE
SkyFactory is not opening the minecraft launcher

### ISSUE THREAD

**Issue by stillj2** [DarkPacks/SkyFactory-4#1498]
## Bug Description

I am trying to open SKyFactory 4 but every time I click play in the Twitch launcher, it opens up a file called Main and this file says it is a minecraft launcher but its not. When trying to play the game from this file is give me a message that says 
"Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)"
How do I fix this issue so that it opens in the Minecraft launcher and doesn't give me this message??

### Did this behavior use to work in the previous version?

 I have never installed SkyFactory 4 before

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
When clicking play, Twitch will open one of two programs. Both of which are Minecraft Launchers produced by Mojang.

The default is the new Native Launcher that looks something like this:
![2019Launcher](https://user-images.githubusercontent.com/23245543/85971602-85a37780-b9c5-11ea-9f00-1c2a1952bc01.png)

The second is the older Jar Launcher that looks like this:
<img width="900" alt="Screenshot 2020-06-29 at 04 57 16" src="https://user-images.githubusercontent.com/23245543/85971641-a4097300-b9c5-11ea-8f5e-52efb6603b1b.png">

You choose which in Twitch's settings.

Your error sounds like it s caused by switching to the Jar launcher and combining it with a version of Java that is unsupported by Minecraft Forge for 1.12.2. You must use Java version 8.

You can change the version of Java used in Twitch's settings, or switch back to the Native Launcher, which uses a (very old) bundled version of Java 8.

For further help with this, please use the Discord https://discord.gg/darkosto
