### ISSUE TITLE
Lag wont stop

### ISSUE THREAD

**Issue by MrCrazyderp** [DarkPacks/SkyFactory-4#1677]
I have opened and looked forward to playing Sky Factory 4. However, since i started playing i have not stopped lagging even after changing settings. Any ideas what is wrong? I have 42.5 gb free so that musnt be the problem. Any ideas on how to get my game to run smoother?
Thanks,
Tyler

**Comment by MrCrazyderp** [comment]
With all due respect, what template?

**Comment by sam-kirby** [comment]
> With all due respect, what template?

When creating an issue in this repository, you should have been presented with the following list of templates:
![image](https://user-images.githubusercontent.com/23245543/95107010-3a6dd300-0731-11eb-8055-6ada50da91f9.png)

Regardless, this issue is best addressed in a more interactive setting - you should join the Discord server at https://discord.gg/darkosto and make a post there. Please include details such as your RAM allocation and total system RAM.
