### ISSUE TITLE
help

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#1733]
I was playing sky factory 4 and things started to disappear but they still worked I couldn't stop this  please tell me the answer 
its quite annoying

**Comment by harrobe123** [comment]
someone please plz put on the tag BUG

**Comment by sam-kirby** [comment]
You have not given us enough information to work on this as a bug.

At a bare minimum, we would need to understand what it is you're experiencing. Unspecified things disappearing but working tells me nothing useful.

Ideally, though not required, you'd also provide us with the minimum set of steps we could use to reproduce the issue on our own machines. This makes fixing things a ton easier as we can then probe an issue in much more detail.

We need to understand why an issue is occurring to be able to fix it.

From your report, the only thing I could possibly suggest is updating your graphics drivers and try reinstalling the pack. Which is support. Which is why I directed you to Discord, where people may be able to guide you through the process.

This issue will not be reopened. Please open a new issue and fill out as much information as possible from the template if you wish to have this investigated.

Thank you.
