### ISSUE TITLE
Backup File size

### ISSUE THREAD

**Issue by ryanmcdon** [DarkPacks/SkyFactory-4#1747]
Hey I am playing on a Mac in the Twitch launcher.
I got an alert (about a week ago) after playing SkyFactory 4 for about 20 hours. My computer alerted my that I was running out of space on my hard drive, After looking threw my files I found backups for this mod had started small (about 1-3 mb) but at some point had drastically increased to 5gb per backup. I unfortunately deleted all the files except the most recent backup    so that I could keep playing. However I thought I should let you know about this issue. If you would like the recent version backup I could upload it (if GitHub doesn't mind the size)

I am on Mac, Using most recent Java version (Java 8 update 271)
I have recently switched to the curse forge launcher new backups are still about 5 gb

**Comment by sam-kirby** [comment]
The size of your backup will increase as the size of your world grows - if you generate other dimensions (particularly if they have terrain) then this will contribute significantly to the size of your backups. There's not really anything that can be done to change this as it would be quite unexpected if the backup only stored some of the world.

You can alter the config of the backup mod such that it stores fewer previous backups, or so that it does incremental backups (only backing up things that have changed since the last full backup). Note that it is much harder to restore an incremental backup.

**Comment by ryanmcdon** [comment]
Sam-kirby, the only reason I believe this is some bug from a mod is because 5gb is way more then I could possibly have loaded chunks, I tried flying out to -4000,-4000 in a new mystcraft world (not a void world) and it only added about ~30mb to the backup size. In most worlds (neather,end,twighlight forest, other mystcraft worlds) I have traveled only to about 1000 blocks in any direction. The backup mod config is a huge help tho because I was manually deleting all of the files before!

**Comment by ryanmcdon** [comment]
Figured it out. I had over 5000 duplicate files inside my save file (total every file was duplicated 50 times) I deleted them and my world ran fine. Backups are now 40.3 mbs (I also deleted a couple mystcraft worlds I used only to find pages)

**Comment by sam-kirby** [comment]
Glad you got to the bottom of it.
