### ISSUE TITLE
im not sure if there has been a fix yet already but I've been searching for i think 2 days and haven't found a solution but the skyorchards crafting file/script dose not exist ive been trying to do it by my self and reaserching but i have stoped i only need the requiered file

### ISSUE THREAD

**Issue by lorax-2465** [DarkPacks/SkyFactory-4#1819]
### Did this behavior use to work in the previous version?
i i have the same problem with playing on the terrafirmacraft tng which is new i have been able to play it before starting to play sf4

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: sky factory 4
* Prestige Enabled: no
* Modpack Version world created in: most recent (as of 1/22/21)
* Additional Content Installed: none

## Client Information
* Modpack Version: latest (as of 1/22/21)
* Java Version: 1.12.2
* Launcher Used: curse forge
* Memory Allocated: 4 GB
* Server/LAN/Single Player: single player gives error as if i tried to join a server
* Optifine Installed: no optifine
* Shaders Enabled: no shaders

**Comment by lorax-2465** [comment]
i also do not mean to break the tos or infringe/steal this modpack i only mean good intentions if you want me to undo some changes i made just tell me darkosto

**Comment by sam-kirby** [comment]
I'm really confused about what you're trying to do here.

Terrafirmacraft TNG is a completely unrelated project and has nothing to do with Sky Orchards.

There has never been a version of the pack shipped without Sky Orchards recipes. Nothing is broken here, so there is nothing to fix.

There is no single script listing all Sky Orchards recipes. We wrote a generator for these recipes due to their similarity.

What changes have you made? What are you trying to do?

**Comment by shattyyt** [comment]
Also having this problem, cannot craft dirt from resin.

**Comment by sam-kirby** [comment]
Closing as unclear what original poster was trying to achieve.

@shattyyt you should probably post your own issue, or use the discord server's support section https://discord.gg/darkosto
