### ISSUE TITLE
Electrolytic separator making liquid oxygen instead of oxygen.

### ISSUE THREAD

**Issue by p0w3rc0r3** [DarkPacks/SkyFactory-4#1923]
## Bug Description
So I want to make a system that makes calcium but I think there is a bug. https://prnt.sc/14125bc in the link you can see its making hydrogen like it should be but https://prnt.sc/1412az0 in this link you can see it makes liquid oxygen.

## Steps to Reproduce (for bugs)

1. Set up an electrolytic separator that has power and water.
2. Extract the oxygen with pressurized tubes into chemical reactors.
3. The chemical reactors should have liquid oxygen in them after the first 2 steps.

## Logs

* Client/Server Log:
* Crash Log: Has not crashed

## World Information
* World Preset: Default
* Prestige Enabled: No
* Modpack Version world created in:4.2.2
* Additional Content Installed: No

## Client Information
* Modpack Version: 4.2.2 (on curseforge)
* Java Version: https://prnt.sc/1413djp - maybey this works I really dont know this stuff.
* Launcher Used: Default premium minecraft
* Memory Allocated:
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: None

**Comment by sam-kirby** [comment]
This is intentional.

Mekanism adds its own gas system. Nuclearcraft is designed to work without Mekanism and so does not fully utilise this gas system. Instead it primarily relies on Forge's fluid system which ensures good compatibility with other mods.

In an effort to not confuse players, it accepts the gases from Mekanism but converts them to a suitable liquid form that works as a Forge fluid.

All chemical reactor recipes will work as intended with Liquid Oxygen in the tank in this pack.

Attached is a screenshot showing this recipe functioning as intended with "liquid oxygen".

![image](https://user-images.githubusercontent.com/23245543/120839482-e5ed5280-c560-11eb-8e76-7ce07db3a279.png)

![image](https://user-images.githubusercontent.com/23245543/120839418-d1a95580-c560-11eb-8418-19f7898a49b9.png)
