### ISSUE TITLE
Missing bedpatch mod but actually not

### ISSUE THREAD

**Issue by ahdiua** [DarkPacks/SkyFactory-4#1927]
## Bug Description

cant join the server which i created

### Did this behavior use to work in the previous version?

didnt play previous version

## Steps to Reproduce (for bugs)

1.install a new winserver 2019 and instill java 8
2.unzip the server file
3.launch the install.bat
4.launch the severstart.bat
5.connect to the server

## Logs

* Client/Server Log:Server Log: [latest.log](https://github.com/DarkPacks/SkyFactory-4/files/6646749/latest.log) [debug.log](https://github.com/DarkPacks/SkyFactory-4/files/6646752/debug.log) Client log:[latest.log](https://github.com/DarkPacks/SkyFactory-4/files/6646754/latest.log)
* Crash Log:[16:18:04] [Netty Server IO #3/INFO] [FML]: Attempting connection with missing mods [bedpatch] at CLIENT

## World Information
* World Preset:no
* Prestige Enabled:no
* Modpack Version world created in:4.2.2
* Additional Content Installed:

## Client Information
* Modpack Version:4.2.2
* Java Version:jre-8u291
* Launcher Used:CurseForge
* Memory Allocated:4G
* Server/LAN/Single Player:Server
* Optifine Installed:no
* Shaders Enabled:no

## Server Information
* Java Version:jre-8u291
* Operating System:Windos Server 2019
* Hoster/Hosting Solution:Alibaba Clouda
* Sponge (Non-Vanilla Forge) Server:no

**Comment by sam-kirby** [comment]
`bedpatches` is a server only mod, the client does not load it and so it shows as missing. This is expected behaviour, and will not cause the connection attempt to fail.

The reason for the failed connection is in the client log. There are a bunch of mismatched registry entries - see line 13548 onwards. This usually means that the server was setup using only the `mods` folder, and as a result the configuration is reset to default.

As an example: in this pack, the Sky Stone Chest from Applied Energistics 2 is supposed to be disabled, but on line 13638 of your client's log it shows up as having being registered on the server.

This means your server is not configured correctly. Make sure you include all folders from the server zip in the server directory.

If you need help, you'd be better off using the Discord - you will usually get a quicker response - though you can keep replying here if you'd prefer.

https://discord.gg/darkosto
