### ISSUE TITLE
Applied Energistics Problem. Can't craft more than 17 or 18. 

### ISSUE THREAD

**Issue by Lord-Volkner** [DarkPacks/SkyFactory-4#2030]
## Steps to Reproduce (for bugs)

1. Put thousands of iron ingots into the system.
2. Set 9 iron ingots into the crafting grid of a crafting terminal to make a block of iron.
3. Shift click on the block of Iron to make a full stack.
4. It won't make the full stack. It will make 16 to 18 and then the crafting grid won't completely refill. You have to manually refill the grid to make more.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
This is not a bug, this is an intentional design choice by Applied Energistics. Below is the explanation.

Every time you try to take an item out of the AE system, it requires energy. For every iron block you want to craft, you need to take out 9 iron ingots.

Crafting 18 iron blocks requires withdrawing 162 iron ingots. This uses up all the energy in the energy acceptor.

Add more energy storage to your network to be able to withdraw more items at a time. A few dense energy cells should do the trick.

More info: https://appliedenergistics.github.io/features/me-network/network-energy
