### ISSUE TITLE
Crashing for no reason, LAN server

### ISSUE THREAD

**Issue by Tosiek99** [DarkPacks/SkyFactory-4#2109]
## Bug Description
Server just randomly crash.

### Did this behavior use to work in the previous version?
I don't know.

## Steps to Reproduce (for bugs)
1. Do nothing
I have only used auto bonsai pot/ item extractor cable.
https://youtu.be/01OmT-1dHdA

## Logs
* Client/Server Log: https://www.mediafire.com/file/qgtb3ip7rhumkjv/logs.rar/file
* Crash Log: https://www.mediafire.com/file/qgtb3ip7rhumkjv/logs.rar/file

## World Information
* World Preset: default
* Prestige Enabled: default 
* Modpack Version world created in: 07.05.2022
* Additional Content Installed: no 

## Client Information
* Modpack Version: 4.2.4
* Java Version: 8 
* Launcher Used: curseforge
* Memory Allocated: 6gb
* Server/LAN/Single Player: LAN
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: 8 
* Operating System: Windows 
* Hoster/Hosting Solution: PC
* Sponge (Non-Vanilla Forge) Server: default ( from curseforge )

**Comment by Tosiek99** [comment]
Edit: After removing Auto Clicker from my base, crashes won't occur again.

**Comment by sam-kirby** [comment]
You have an auto clicker right clicking on a cake - teleporting the block fails because it isn't really a player; using Forge's facility to remove erroring tile entities should help you resolve this and recover your world.

If you need help with this, it is best to ask on the Discord server at https://discord.gg/darkosto as it can take a while to respond to posts here.
