### ISSUE TITLE
Login/Server Issue: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connect refused: no further information: 

### ISSUE THREAD

**Issue by FullSoorma** [DarkPacks/SkyFactory-4#2261]
## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Launcher Used:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

To be clear, I am not the server owner, he will not be available for a few days so was attempting to resolve the issue my self. This is my first attempt and am not aware on how to get all the information required for this form. 
![image_2023-10-25_173024674](https://github.com/DarkPacks/SkyFactory-4/assets/148942068/5b83ec1b-135c-4960-8535-b326e1cb636d)

![image_2023-10-25_173059935](https://github.com/DarkPacks/SkyFactory-4/assets/148942068/851d726d-89a0-4f32-83fe-3ab0e1a00562)

![image_2023-10-25_173332801](https://github.com/DarkPacks/SkyFactory-4/assets/148942068/2c5edfca-d023-483d-8be6-4da73d7fa028)

**Comment by sam-kirby** [comment]
Hi, there isn't really enough information here to make a proper assessment, but I'll do my best. I'm having to make some assumptions, namely that your friend is hosting the server from their house on their own computer, and that nobody is able to connect to the server from outside your friend's house. This is because "Connection refused" indicates a network issue, usually caused by one of the following problems (from most to least common):-

1. The server is not running
2. The server operator has not setup port forwarding properly; the server will only be accessible from their network (i.e. connected to their wifi)
3. The server operator has given you a private IP address when they should have given you their public IP address. An address that starts `192.168.`, `172.16-31.` or `10.` is a private IP address and will only work on their network
4. A firewall blocked the connection, usually on the server but this could also be on your computer or something in between such as parental controls
5. Your friend's ISP uses carrier grade NAT and so can't host a server without additional steps such as requesting a static IP or setting up a tunnel. If they've given you an address that starts `100.64.` then this is likely the case.

Unfortunately, most of these issues need to be resolved by the server operator, but you can point them to the Discord server for help if they need it: https://discord.gg/darkosto
