### ISSUE TITLE
Advancements arent working in a hosted server.

### ISSUE THREAD

**Issue by Dillplays** [DarkPacks/SkyFactory-4#2291]
## Bug Description
advancements dont show up in game, in server console its says " 'sf4:age1/sapling/gravel' in progress file ./New World/advancements/a3cf93fb-1cb9-42c6-ab97-35453845c497.json - it doesn't exist anymore?" for the advancements, the actual advancements json file just resets to basic 1.12.2 or doesnt work every time i try to fix it

### Did this behavior use to work in the previous version?
Didnt try

## Steps to Reproduce (for bugs)=
1. move entire world folder over with file manager from working single player world (with server pack already in)
2. start server
3. console give a list of errors listing what i put before
4. in the game the advancement book gui either says something went wrong, or shows basic 1.12.2 advancements

## Logs
https://mcpaste.io/888ab87b8eb0b731

## World Information
* World Preset: default
* Prestige Enabled:default
* Modpack Version world created in: 4.2.4
* Additional Content Installed: none

## Client Information
* Modpack Version:4.2.4
* Java Version:8.0.4010.10
* Launcher Used: curseforge
* Memory Allocated: 8gb
* Server/LAN/Single Player: server (pebblehost)
* Optifine Installed:none 
* Shaders Enabled: none

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Based on the provided logs, you are running a vanilla server. Advancements are loaded through a mod (triumph), which will not work on a vanilla server, so the server considers them not to exist.

Further, you shouldn't need to copy a single player world to a properly configured server. It is able to generate any of the world types available in single player; you can choose which by setting up server.properties as described in the [Multiplayer Instructions](https://github.com/DarkPacks/SkyFactory-4/wiki/Multiplayer-Instructions).

It looks like pebblehost has an automatic modpack installer, so I'd start by trying that. Otherwise, you can download the server pack from Curseforge, run the installer on your own computer, rename the forge jar to custom.jar and then upload everything to pebblehost, including all the mods, configs and scripts.
