### ISSUE TITLE
Sync mod: Original body vanishes from storage

### ISSUE THREAD

**Issue by VeryPeeved** [DarkPacks/SkyFactory-4#2300]
Was playing on the "Are You Afraid of the Dark" preset, which starts you off with a small Sync cloning setup. Immediately after spawning, I started the machine on building a clone. Once it was complete, I walked into the storage to make sure it was functioning properly. Apparently, it wasn't, since immediately after taking control of the clone, the original body simply vanished in front of my eyes, along with everything in its inventory.

**Comment by VeryPeeved** [comment]
The template is completely stupid. It has as much worth as those garbage minimum page requirements on school essays: which is to say, none whatsoever. Issues, just like essays, should provide precisely as much text as is needed to accomplish their goal, and not a character more or less. But I guess a worthless, arrogant, poorly thought out bug report page fits well with this worthless, arrogant, poorly thought out modpack.

That's what comes of people trying to create while being pants-shittingly terrified of introspection.

**Comment by sam-kirby** [comment]
The listed steps don't mention any action being taken to keep the storage powered with a redstone signal. As noted in the advancement "Through the looking glass", the shell storage will fail, deleting the shell permanently, if it is ever unpowered. It sounds like you are relying on the pressure plate, which unpowers shortly after you step off it.

> That's what comes of people trying to create while being pants-shittingly terrified of introspection.

Haha, no. This is what happens when 100s of people open issues without enough information to be actionable, leading to wasted time going back and forth trying to work out whether they are even playing the latest version, for example. Back when releases were frequent, it wasn't uncommon for people to be playing old versions and report bugs that were already fixed for example. And the number of people who would say "I have a crash report if you need it" was silly, so we gave steps to upload it.
