### ISSUE TITLE
AE2 Energy Cell Crash

### ISSUE THREAD

**Issue by Tapeman83** [DarkPacks/SkyFactory-4#637]
## Bug Report
 For some reason, when I placed an AE2 Dense Energy Cell onto an active flux point (the one that gives energy to objects), the game crashed, and crashed every time I attempted to load in, providing an "exception in server tick loop" error. 

## Expected Behaviour
 It crashes the game instead of just injecting energy into the energy cell.

## Steps to Reproduce (for bugs)

1. Place an AE2 Dense Energy Cell on a live flux point.
2. Crash loop.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/ay9BV3RY

## World Information

* Preset: Standard void world.

* Prestige: Yes.

* Modpack Version world created in: 4.0.0, currently running 4.0.3.

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.3
* Java Version:
* Launcher Used: Twitch launcher.
* Memory Allocated: 8GB. 
* Server/LAN/Single Player: Single Player. 
* Optifine Installed: No. 
* Shaders Enabled: No. 

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by JackRuby1** [comment]
https://github.com/SonarSonic/Flux-Networks/issues/284 It's been reported over to the Flux Networks github.

**Comment by kythorn** [comment]
Until the mods address it, I suggest the pack edit flux networks configs to blacklist the energy and dense energy cell.

**Comment by sk2048** [comment]
Thank you Kythorn, that's a good idea.

**Comment by Gunner76th** [comment]
Since I see the above suggestion has not been implemented as a config change as of yet in release version 4.0.8, I assume this is because its level of importance was either deemed too low to be addressed within the last 60 days? 

For anyone who comes here for this problem, copy and replace the blacklist section of the fluxnetworks.cfg file with the text provided below. 

To prevent this crash, you need to blacklist AE energy cells as well as the energy acceptor in the Flux Network config. The config change is supplied below, copy it and replace what is in your current config in the blacklist section. 

```
blacklists {
    # a blacklist for blocks which flux connections shouldn't connect to, use format 'modid:name'
    S:"Block Connection Blacklist" <
        actuallyadditions:block_phantom_energyface
	appliedenergistics2:energy_acceptor
	appliedenergistics2:dense_energy_cell
	appliedenergistics2:energy_cell 
     >

    # a blacklist for items which the Flux Controller shouldn't transfer to, use format 'modid:name'
    S:"Item Transfer Blacklist" <
	appliedenergistics2:energy_acceptor
	appliedenergistics2:dense_energy_cell
	appliedenergistics2:energy_cell 
     >
}

```

**Comment by Jerakl** [comment]
> Since I see the above suggestion has not been implemented as a config change as of yet in release version 4.0.8, I assume this is because its level of importance was either deemed too low to be addressed within the last 60 days?
> 
> For anyone who comes here for this problem, copy and replace the blacklist section of the fluxnetworks.cfg file with the text provided below.
> 
> To prevent this crash, you need to blacklist AE energy cells as well as the energy acceptor in the Flux Network config. The config change is supplied below, copy it and replace what is in your current config in the blacklist section.
> 
> ```
> blacklists {
>     # a blacklist for blocks which flux connections shouldn't connect to, use format 'modid:name'
>     S:"Block Connection Blacklist" <
>         actuallyadditions:block_phantom_energyface
> 	appliedenergistics2:energy_acceptor
> 	appliedenergistics2:dense_energy_cell
> 	appliedenergistics2:energy_cell 
>      >
> 
>     # a blacklist for items which the Flux Controller shouldn't transfer to, use format 'modid:name'
>     S:"Item Transfer Blacklist" <
> 	appliedenergistics2:energy_acceptor
> 	appliedenergistics2:dense_energy_cell
> 	appliedenergistics2:energy_cell 
>      >
> }
> ```

This worked for me, thanks. 

This issue just happened for the 2nd time on the server I run (the first time it fixed itself?). There's an issue on the flux networks github that has been open for LITERALLY 6 MONTHS with no reply from the author and multiple replies saying they have the same issue. No updates for fluxnetworks or Sonarcore since dec 2018. Can only assume the author has actually died.
