### ISSUE TITLE
Chunks with certain blocks (e.g. a Cauldron) do not unload. (SP/Server)

### ISSUE THREAD

**Issue by DerSoftwerker** [DarkPacks/SkyFactory-4#887]
## Bug Report

Chunks in the world will remain active if there are certain blocks present. (e.g. Cauldrons). This is especially problematic for Community Servers with 20+ people being active throughout the day by keeping each and every base loaded and partially loading them up right after a server start without any chunkloaders present.

I did a test on a a fresh installation via Twitch and Singleplayer mode. I build serveral chunks about 300 blocks away from the base with only a furnace, cauldron and/or hopping bonsais. The furncaces were loaded with one stack of charcoal and one stack of cobblestone. Here is what they did smelt:

Base: 64
Furnace: 2
Furnace+Cauldron: 64
Furnace+2xCauldron: 64
Furnace+Bonsai: 4
Furnace+2xBonsai: 4
Furnace+2sBonsai+2xCauldron: 64

So clearly some chunks were not unloaded although not in range. It appears that certain ticking blocks cause the chunk to stay active. It is unlikely only a problem with cauldrons. On my Server I deleted the cauldron mod, restarted and confirmed to delete all cauldrons - but the load right after start was over 20ms/tick (on a 3,7 Ghz Processor) because several chunks were still active. Chunkloaders were deactivated via config and no player had logged in.

Here is the SP map used for testing.
[Chunk Loading Test.zip](https://github.com/Darkosto/SkyFactory4Issues/files/3159658/Chunk.Loading.Test.zip)

## Expected Behaviour

Once a player logs off or gets out of range and there is no chunkloader present, the chunk should become incative, freeing up much needed CPU Power.

## Possible Solution

Unclear. 

## Steps to Reproduce (for bugs)

1. Place a Furnace and a Cauldron in a chunk
2. Load furnace with coal and Cobblestone
3. Leave render range or log off for a few Minutes
4. Stone will be smelted although the chunk should have been inactive

## World Information

* Preset: Sky Factory 4

* Prestige: Server yes, client test no

* Modpack Version world created in: Server 4.0.1, client 4.0.5

* Additional Content Installed:
Server: 
FTBUtilities, Chunkloading disabled
LagGoggles

Client Test:
None

## Client Information

* Modpack Version: 4.0.5
* Java Version: Java 8 201
* Launcher Used: Twitch
* Memory Allocated: 12GB
* Server/LAN/Single Player: Server/SP
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: Java 8 201
* Operating System: Linux
* Hoster/Hosting Solution: Gamed.de
* Sponge (Non-Vanilla Forge) Server: none, Forge Server

**Comment by Yorkforce** [comment]
This for us (we host 5 SF4 servers) is by far the biggest issue we are having right now, we are having to spend multiple hours per day trying to keep TPS up due to chunks not unloading, whats even worse is some chunks are being auto loaded straight after server startup, cauldrons for example are one of the worst causes because if they are spewing out cobble due to auto setups the server TPS can drop instantly as soon as the server comes back online (I don't know if its actually cauldrons causing the chunks to load) 
It's becoming exhausting having to deal with on a daily basis tbh.

As a result we have already lost alot of players.

**Comment by DerSoftwerker** [comment]
I too had to close the whitelist. Even though there are capacities left. Even with all chunkloaders disabled (mekanism,weirdinggadet via config), the server runs right after starting up with 45-50 ms/tick while no one is active. (3,7 Ghz Server)

Sadly there has been no reaction to this isssue since I opened it over a month ago and I am starting to get tired trying to optimize the server every other day.

**Comment by KnightMiner** [comment]
This is definitely not an issue with cauldrons, they are not a ticking block. Everything with them happens either on entity collision (meaning entity tick, entities must be loaded) or on player interaction. Are you sure you actually unloaded the chunks, and the cauldron is not in the spawn chunks?

**Comment by sk2048** [comment]
For the record, no comments often just mean we've got nothing productive to say and have no idea where the issue lies. I've spent at least 8 hours trying to find the source of this issue. I'm sure others on the team are treating this equally seriously and I know resolving this is a high priority for Darkosto.

**Comment by sk2048** [comment]
Mrbysco/MoreCauldrons@ce4f848a62afa79cce1def690e6356503929b8f5
